version: '2.1'

services:

  query_db_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      AUTH0_DOMAIN: "registree.eu.auth0.com"
      API_IDENTIFIER: "https://registree.rocks/apis"
      ALGORITHMS: "['RS256']"
      BIGCHAINDB_URL: "http://bigchaindb_api:8000/v0.1"
    depends_on:
      - mongodb
    networks:
      - backbone
      - apiaggregator_interconnector
      - bigchaindbapi_backbone

  mongodb:
    image: mongo:3.6
    command: mongod
    networks:
      - backbone
    volumes:
      - ./mongodata:/data/db
      
networks: 
  backbone:
    driver: bridge
  bigchaindbapi_backbone:
    external: true
  apiaggregator_interconnector:
    external: true
