version: '2.1'

services:

  query_db_api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:8000"
    environment:
      AUTH0_DOMAIN: "registree.eu.auth0.com"
      API_IDENTIFIER: "https://registree.rocks/apis"
      ALGORITHMS: "['RS256']"
      STUDENT_DB_URL: "http://student-db-api:8000/v0.1"
    depends_on:
      - mongodb
    networks:
      - backbone

  mongodb:
    image: mongo:3.6
    command: mongod
    ports:
      - "27018:27017"
    networks:
      - backbone
      
networks: 
  backbone:
    driver: bridge

