version: '2.1'

services:

  query_db_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    env_file:
      - api.env
    depends_on:
      - mongodb
    networks:
      - backbone
      - apiaggregator_interconnector
      - studentnftapi_backbone

  mongodb:
    image: mongo:3.6
    command: mongod
    env_file:
      - mongo.env
    networks:
      - backbone
    volumes:
      - ./mongodata:/data/db
      
networks: 
  backbone:
    driver: bridge
  studentnftapi_backbone:
    external: true
  apiaggregator_interconnector:
    external: true
